server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30
# 日志配置
logging:
  level:
    com.amy: debug
    org.springframework: warn
# Spring配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: druid
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.amy.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mybatis/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

custom:
  wx:
    appId: "wxddde47b1b01e63ed"
    appIdSecret: "b8da7ff94aad27817be9baede3442599"

wx:
  pay:
    appId: "wx2ed3a9f90501e9fd"
    mchId: "1595823611"
    mchKey: "aabae70c854e5009dc39e9a14aa013c7"
